-- SQL Server schema for DevFlow backend

CREATE TABLE Users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(150) NOT NULL,
  email NVARCHAR(255) NOT NULL UNIQUE,
  password NVARCHAR(255) NOT NULL,
  gender NVARCHAR(20) NOT NULL DEFAULT 'Other',
  country NVARCHAR(100) NOT NULL DEFAULT '',
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Projects (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(150) NOT NULL,
  description NVARCHAR(MAX) NOT NULL DEFAULT '',
  type NVARCHAR(50) NOT NULL DEFAULT 'Other',
  icon NVARCHAR(20) NOT NULL DEFAULT '🚀',
  color NVARCHAR(20) NOT NULL DEFAULT '#f3eeff',
  createdBy INT NOT NULL,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Projects_Users FOREIGN KEY (createdBy) REFERENCES Users(id)
);

CREATE TABLE Tasks (
  id INT IDENTITY(1,1) PRIMARY KEY,
  title NVARCHAR(255) NOT NULL,
  status NVARCHAR(20) NOT NULL DEFAULT 'todo',
  project INT NOT NULL,
  createdBy INT NOT NULL,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Tasks_Projects FOREIGN KEY (project) REFERENCES Projects(id),
  CONSTRAINT FK_Tasks_Users FOREIGN KEY (createdBy) REFERENCES Users(id)
);

CREATE TABLE Docs (
  id INT IDENTITY(1,1) PRIMARY KEY,
  title NVARCHAR(255) NOT NULL,
  content NVARCHAR(MAX) NOT NULL DEFAULT '',
  project INT NOT NULL,
  createdBy INT NOT NULL,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Docs_Projects FOREIGN KEY (project) REFERENCES Projects(id),
  CONSTRAINT FK_Docs_Users FOREIGN KEY (createdBy) REFERENCES Users(id)
);

CREATE TABLE Repos (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(255) NOT NULL,
  link NVARCHAR(500) NOT NULL,
  language NVARCHAR(50) NOT NULL DEFAULT 'Other',
  project INT NOT NULL,
  createdBy INT NOT NULL,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Repos_Projects FOREIGN KEY (project) REFERENCES Projects(id),
  CONSTRAINT FK_Repos_Users FOREIGN KEY (createdBy) REFERENCES Users(id)
);
